#include "../lib/math/integral/arithmetic_function/divisor.hpp"
#include "../lib/math/integral/arithmetic_function/euler_totient.hpp"
#include "../lib/math/integral/arithmetic_function/prime_omega.hpp"

#include "../lib/math/integral/basic_operation/bit.hpp"
#include "../lib/math/integral/basic_operation/div/include.hpp"
#include "../lib/math/integral/basic_operation/gcd.hpp"
#include "../lib/math/integral/basic_operation/is_palindrome.hpp"
#include "../lib/math/integral/basic_operation/log10.hpp"
#include "../lib/math/integral/basic_operation/pow.hpp"
#include "../lib/math/integral/basic_operation/sqrt/include.hpp"

#include "../lib/math/integral/basic_operation/is_prime/miller_rabin.hpp"
#include "../lib/math/integral/basic_operation/is_prime/trial_division.hpp"

#include "../lib/math/integral/basic_operation/factorization/all.hpp"
#include "../lib/math/integral/basic_operation/factorization/prime.hpp"
#include "../lib/math/integral/basic_operation/factorization/prime_minp.hpp"

#include "../lib/math/integral/sieve/eratosthenes.hpp"
#include "../lib/math/integral/sieve/linear/base.hpp"
#include "../lib/math/integral/sieve/linear/closest_prime_list.hpp"
#include "../lib/math/integral/sieve/linear/divisor_function_list.hpp"
#include "../lib/math/integral/sieve/linear/euler_totient_function_list.hpp"
#include "../lib/math/integral/sieve/linear/largest_prime_factor_list.hpp"
